//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }
    
        public int ProdId { get; set; }
        public string ProdName { get; set; }
        public string ProdManufacturer { get; set; }
        public string ProdPrice { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
    }
}
